# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
# neumorphic
username: Aiden Benton
typing_text: Developer, Musician, Privacy Enthusiast
email: contact@aiden-benton.com
github_username: intothebeans
linkedin_username: aiden-benton
show_aboutme_card: true
about_me_description:
show_skills_card: true
skills_title: Skills and Strengths
show_timeline_card: true
timeline_title: Education and Experience
show_projects_card: true
show_projects: true
projects_title: Projects
show_os_projects: true
os_projects_title: Open Source Projects
show_contact_card: true
contact_title: Contact
contact_description: Feel free to reach out to me with any questions or opportunities.
projects:
  sort_by: pushed
  exclude:
    archived: true

minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale: "en-US"
title: "Aiden Benton"
title_separator: "|"
subtitle: # site tagline that appears below site title in masthead
name: "Aiden Benton"
description: "Aiden Benton's personal website sharing projects and ideas."
url: # TODO: update for production # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: # the subpath of your site, e.g. "/blog"
repository: "intothebeans/intothebeans.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser: "/assets/images/teaser-fallback.jpg" # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo: "/assets/images/logo-88x88.png" # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title: " " # overrides the website title displayed in the masthead, use " " for no title
breadcrumbs: # true, false (default)
words_per_minute: 200
enable_copy_code_button: true # true, false (default)
copyright: # "copyright" name, defaults to site.title
copyright_url: # "copyright" URL, defaults to site.url
comments:
  provider:
atom_feed:
  path: # blank (default) uses feed.xml
  hide: # true, false (default)
search: true
search_full_content: true
search_provider: algolia
algolia:
  application_id: 7TASFM3UFH
  index_name: bbb
  search_only_api_key: 95de4083ee2f74557ece20b67a861910
  powered_by: true

# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type: # Person or Organization (defaults to Person)
  name: # If the user or organization name differs from the site's name
  links:
    - "https://linkedin.com/in/aiden-benton"
    - "https://github.com/intothebeans"

# Analytics
analytics:
  provider: false

# Site Author
author:
  name: "Aiden Benton"
  avatar: "/assets/images/glitched-add.gif"
  bio: "*Developer, Musician, Privacy Enthusiast*"
  location: "Virginia, USA"
  email: "contact@aiden-benton.com"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/aiden-benton"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/intothebeans"

# Site Footer
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/aiden-benton"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/intothebeans"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - .env
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
timezone: America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Pagination with jekyll-paginate
paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-github-metadata

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-github-metadata

# Archives
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

header_scripts:
  - https://buttons.github.io/buttons.js
